### ISSUE TITLE
Entities not spawning on snow covered blocks

### ISSUE THREAD

**Issue by Dulciphi** [ProjectZulu/JustAnotherSpawner#102]
I'm having trouble getting passive CREATURE spawns in snow-covered biomes. "Effectivespawnlist" confirms the CREATUREs just can't spawn. I'm unsure whether this affects spawning on all non-solid blocks. I *was able to get Penguins to spawn in the OPENSKY group but, as I would only want the OPENSKY group for my COLD BiomeGroup, this is sub-optimal. I have (possibly needlessly) wondered if allowing the LivingHandler to override the CreatureType tags would help here? but I'm really not sure. I can't think of any more tags to try. Modspawn, legacy.light, !(sky()), block.. I don't know

**Comment by LavaSlayer** [comment]
I am seeing the same issue (creatures not spawning on the snow layer).  Here is the default spawn tag in the CreatureType.cfg:
"Spawn Tag": "!solidside(1,{0,0,0},{0,-1,0})||liquid({0,0,0},{0,0,0})||normal({0,0,0},{0,0,0})||normal({0,0,0},{0,1,0})||!opaque({0,0,0},{0,-1,0})||!sky()",
With this spawn tag, I see creatures spawn on grass blocks underneath the sky, but there is no spawning on snow-covered blocks.  Also, nothing spawns on grass blocks that are underneath tree leaves.
I tried changing the sky() in that spawn tag to ground().  In that case, creatures were able to spawn on blocks underneath tree leaves.  However, there were still no spawns upon snow-covered blocks.
I believe that the following line in CreatureType.cfg is the problem:
"Spawn Medium": "air",
I suspect the spawner is considering the minecraft:snow_layer (the snow layer on top of the grass/dirt/whatever) to be a non-air block, and is consequently not allowing the creatures to spawn where these snow layers exist.
Is there a way to override the "Spawn Medium": "air" requirement?

**Comment by AnvilPuncher** [comment]
Yeah, I was just working on this one.  A workaround for this would be 
"Spawn Tag": "!solidside(1,{0,0,0},{0,-2,0})||liquid({0,0,0},{0,0,0})||normal({0,0,0},{0,-1,0})||normal({0,0,0},{0,0,0})||normal({0,0,0},{0,1,0})||!opaque({0,0,0},{0,-2,0})||!ground()",
replace !ground() for !air() if you want but I like critters spawning in my canopy forests and jungles.  
The drawback is that they will fall one block when spawned and you need 3 vertical blocks for them to spawn.  I concur that this is due to the spawn medium of air not being considered for a block with a snow layer.

**Comment by Dulciphi** [comment]
I like that. I currently have !opaque removed for my creature category but that's hardly ideal. I tried a lot of different combinations but I didn't think to try !ground. I'll be trying that now. Thank you

**Comment by Dulciphi** [comment]
Actually, I can't find remember which issue the discussion was in but you (Crudedragos) mentioned a possible enhancement to have the Living Handler overwrite the settings in CreatureType. 

I believe that would be the ideal fix for this. The issue (at least as I see it) is that the snow tile is an opaque and non-solid block - much like stairs, chests, glass and a raft of other blocks that are not supposed to be spawned upon.

Thus, I currently have my *entire CREATURE CreatureType set to:
    "CREATURE": {
      -snip-
      "Spawn Tag": "!solidside(1,{0,0,0},{0,-1,0})||liquid({0,0,0},{0,0,0})||normal({0,0,0},{0,0,0})||normal({0,0,0},{0,1,0})||!sky()",
      etc..
    },
This is the best compromise I've been able to find for my needs. I've gone through and individually tagged some non-snowy biome CREATURES to only spawn on grass or sand.

Ideally, I'd like to leave the CREATURE CreatureType settings as default, then *overwrite them where applicable. Ie, with the PZ Penguin I'd have something like:
    "ProjectZulu|Core.Penguin": {
      "Type-Enabled": "CREATURE-true",
      "Spawn Operand": "OR",
      "Spawn Tag": "!(block({'snow_layer'},{0},{3,3,3},{0,0,0}))",
      "Contents": [
        "ProjectZulu|Core.Penguin"
      ]
    },

I'm trying to think of spawn conditions that would be otherwise entirely impossible unless the Spawn Operand overwrote the CreatureType's tags as you suggested. I thought of one ages ago but can't recall it now. It would at least make the process much simpler for the user. I'm not sure how possible/feasible it is for you, though.

**Comment by Dulciphi** [comment]
:) thank you. This is working perfectly now.
