### ISSUE TITLE
[Question] Are non-despawnable entities counted in a group spawn cap?

### ISSUE THREAD

**Issue by Boxmanbr** [ProjectZulu/JustAnotherSpawner#104]
I want to create a group with a cap of five entities, but they are tameable, so if I tame all of them and keep them with me anytime would this group keep spawning more entitites until it reach ten, or the entities I tamed should be killed so more would be allowed to spawn?

**Comment by Boxmanbr** [comment]
Is there any way to change that behavior through the config files?

**Comment by Crudedragos** [comment]
Not at this time.

**Comment by Boxmanbr** [comment]
Thanks anyway.
