### ISSUE TITLE
Create Support for Minecraft Comes Alive Specific

### ISSUE THREAD

**Issue by DPxKnightxZero** [ProjectZulu/JustAnotherSpawner#127]
Okay so wild-bama boy doesn't understand the need to make sure 2 million stupid villagers don't have sex and make families all in the same location. Many players have been explaining to him why that is a bad thing but he mostly only uses the mod with his GF and could care less. I was wondering if you because you are more awesome then him because you are understanding of minecraft; could add some very specific compatibility addons related directly to MCA? I would like to control village population cap since he is too stubborn to add a feature to his own mod as well as settings to manage on a per chunk basis how many npcs could be present. I want you to know if a player marries and npc that they should never be flagged for de-spawn. This should only apply to npcs that are not linked to a player in anyway.

Oh yeah you should probably know he something called (ignore story progression but that just creates a dead server. He needs to create an actually setable cap. I don't care about story speed I care my game lags so much it becomes unplayable.)

(Why is talent wasted on the stubborn?)

**Comment by DPxKnightxZero** [comment]
https://github.com/WildBamaBoy/minecraft-comes-alive/issues/301

**Comment by WildBamaBoy** [comment]
You need to keep any issues with MCA within MCA's repository. At this point I don't even know what you are complaining about anymore.

**Comment by Crudedragos** [comment]
@DPxKnightxZero 
I recommend you reconsider your tone when making requests. You know the saying, attract more bees with honey than vinegar. Keep any disputes you have with others simply to the facts of the matter of what is being done / can be done / what you want / what you need.

Villager populations are traditionally done through the vanill spawn system; neither chunk or passive spawning. They are generated with the 'village structure' and are thus outside of JAS's typical scope of control.

The closest JAS could get to allowing control would be if some form of event spawn was added for when entities breed: allowing you to write an expression to consider the total number of entities nearby when deciding if the entity breed successfully.

I'm busy atm so don't expect that functionality soon.

**Comment by Dulciphi** [comment]
Keep it sweet :) Beautiful advice there, as always.

I'm a fan of MCA as well and I've gotta say I'm quite happy with the config. I just delay the time it takes babies and children to grow up and.. life finds a way. I don't think I want my family and I being "flagged for despawn". Vaccines should be free and fair for all lol.

Something that might work with JAS though.. when there's a certain number of MCA entities, have it trigger a spawn event of undead hordes. ;)
