### ISSUE TITLE
Compatibility issues with Creepy Pasta, Alien vs. Predator, and Grimoire of Gaia 3  mods [regarding spawning]

### ISSUE THREAD

**Issue by RodrigoTaipe93** [ProjectZulu/JustAnotherSpawner#135]
Hey, bro! There seems to be an issue with the mod. Whenever I install Creepy Pasta mod, Grimoire of Gaia 3, and Alien vs. Predator together, this crash happens > http://pastebin.com/GfizGyT5 People in the forums of the other mods, point at the Spawn system [J.A.S]. Can you check and tell me if there is any problem or incompatibility with these mods or if there is other problems.

These are the mods I'm using > http://s8.postimg.org/kfk4dj545/Modpack_I.jpg

**Comment by Crudedragos** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288431-just-another-spawner-jas-v0-14?comment=2170
