### ISSUE TITLE
JAS and Erebus (How to get the JAS to ignore a mod)

### ISSUE THREAD

**Issue by keyafay** [ProjectZulu/JustAnotherSpawner#136]
Hello.

I have JAS and a new mod called Erebus. Erebus "hates" any mod that changes spawn rates... for some reason it will stop all spawns in the newly added dimension and is Biomes.

I have been trying to configure JAS to completely ignore Erebus and its Biomes but it hasn't worked.

**Comment by Crudedragos** [comment]
Config/JustAnotherSpawner/BiomeBlacklist.cfg

**Comment by keyafay** [comment]
I have already black listed the Biome's but I still get no spawns

**Comment by Crudedragos** [comment]
Make sure the doMobSpawning gamerule is enabled.

**Comment by Crudedragos** [comment]
This is not an issue on JAS's end. We are mod agnostic.
