### ISSUE TITLE
Help Requested - How to add global spawn cap and mod based spawn caps?

### ISSUE THREAD

**Issue by DPxKnightxZero** [ProjectZulu/JustAnotherSpawner#144]
So I am looking to do a very simple thing ... set a spawn cap for each mod and of course set a global spawn cap for the server and each individual dimension. 

Example Global Spawn Cap 200

Vanilla Spawn Cap - 30
Zelda Sword Skills Spawn Cap - 20
Pokemobs - 20
Advent of Ascention - 20

Etc.

**Comment by Crudedragos** [comment]
Likely the easiest way would be to add a countentities tag to each entity type (which you'd do per mod; Vanilla/Zelda/Pokemob etc).

No matter how large a range you set, in the current implementation, it only checks entities in the loaded entity list for the current dimension.
