### ISSUE TITLE
JAS SLEEP event spawns with Hardmode Tweaks "bed recently placed" feature

### ISSUE THREAD

**Issue by Dulciphi** [ProjectZulu/JustAnotherSpawner#145]
Hewo. I've just opened an [issue](https://github.com/hea3ven/HardModeTweaks/issues/1) over at HardModeTweaks regarding a crash that is probably of my own doing.

Hardmode Tweaks recently updated with a feature that prevents sleep in a bed for three days after the bed has been placed. 

I was using my JAS SLEEP event 
```
[
  {
    "trigger": "SLEEP",
    "expression": "if(sleepResultOk()&&obj.origin>100&&time.timeOfDay<14000){ spawn('Zombie').offset(5).alsoSpawn('shadowmobs.phantom',0,5,0) }"
  }
]
```
I was within 100 blocks of original spawn. Time was after 9pm but I'm uncertain if sleepResultOk was true. Monsters may have been in range. I was essentially just clicking on the bed to test the new feature, as I'd only just placed it. 
Chat returned "[17:26:33] [Client thread/INFO]: [CHAT] This bed was recently placed", then a few seconds later.. crash. [Log](http://pastebin.com/dgSEUDRy).

Could you recommend some steps I can take to get these 2 features working well together? Or at least to work out the exact cause?

**Comment by Crudedragos** [comment]
Closing as this seems to have been resolved on their end.

**Comment by Dulciphi** [comment]
Ah thank you. I should've closed it myself. Indeed it's working well.
