### ISSUE TITLE
Recuresive Chunk Crash

### ISSUE THREAD

**Issue by Crudedragos** [ProjectZulu/JustAnotherSpawner#146]
During chunk spawning, referencing other chunks / blocks in an area can create an infinite loop of needing to check eachother. 

Search functionality cannot be supported for chunk spawns. Chunk spawn tags will need to be changed to a separate expression from passive spawn tags.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288431-just-another-spawner-jas-v0-14?comment=2288

Side effect of #134

**Comment by PitchBright** [comment]
I think you can close this issue. I've not experienced this problem since the latest update.
