### ISSUE TITLE
Ignore feature for mods!

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [ProjectZulu/JustAnotherSpawner#147]
I'm thinking about an ignore feature that entirely disregards certain mods (changeable via file) to be handled by JAS.

Certan mods have very intristic spawn features that unfortunately clash with JAS spawning system. I'd like to be able to disable JAS just for these mods, but still use it for most of my game, because, let's face it, it's THE spawning system mod out there!

**Comment by Crudedragos** [comment]
If the mod has its own spawning system, i.e does not use vanilla then JAS already ignores it.

The default JAS roughly translates (not perfectly) to doing the equivalent of what vanilla does but with the potential to alter things further.

Spawnlists are also weighted lists, removing all vanilla animals from the list would not result in the mod's entities spawning at the author's intended level. Its an all or nothing thing. It only makes sense to ignore an entire Biome of entities.

An biomes can already be ignored.
