### ISSUE TITLE
Crash on tag isClearWeather()

### ISSUE THREAD

**Issue by PitchBright** [ProjectZulu/JustAnotherSpawner#148]
I might be doing this wrong, but I get a crash when I set an Entity's Handler as:

      "InstantDespawn Tags": "(obj.light>7)&&isClearWeather()"

http://pastebin.com/KxF5cXXs

**Comment by Crudedragos** [comment]
"InstantDespawn Tags": "obj.light>7)&&wrld.isClearWeather()" 

It is a world tag so it needs to be wrld.isClearWeather()

**Comment by PitchBright** [comment]
Ah! Thanks man! I'll test and then close this out.

**Comment by PitchBright** [comment]
Sorry I never got around to testing it. My bad.
