### ISSUE TITLE
Squid spawn bug

### ISSUE THREAD

**Issue by WilyMork** [ProjectZulu/JustAnotherSpawner#151]
Sorry for the bad translation .
When the squids spawns in underground reservoirs , a large part of them dies stuck in the blocks . Because of this, the surface of the ink appear .

**Comment by DEX47** [comment]
Looks related to the issue I have just posted.

**Comment by Crudedragos** [comment]
Try https://github.com/ProjectZulu/JustAnotherSpawner/issues/152
