### ISSUE TITLE
1.7.10 - Server Startup Crash

### ISSUE THREAD

**Issue by DPxKnightxZero** [ProjectZulu/JustAnotherSpawner#154]
Crash Log -> Unavailable

Full Log -> https://gist.githubusercontent.com/DPxKnightxZero/59820fb25a211a3c151b/raw/911fa865ec0884562cb3eefb3c002bb1fe4f5735/gistfile1.txt

**Comment by DPxKnightxZero** [comment]
Still waiting on fixes!

**Comment by DPxKnightxZero** [comment]
Still need fixes.

**Comment by LemADEC** [comment]
JustAnotherSpawner isn't the rootcause of your issue. There's another mod messing around with ASM transformations. Remove other mods one by one until you find which one is causing it, than we can discuss about 'fixes'.
