### ISSUE TITLE
NEI F7 overlay

### ISSUE THREAD

**Issue by LemADEC** [ProjectZulu/JustAnotherSpawner#156]
JAS seems to disable NEI F7 overlay as of JustAnotherSpawner-0.17.7 with
- NotEnoughItems-1.7.10-1.0.5.118-universal
- CodeChickenCore-1.7.10-1.0.7.47-universal
- 1.7.10-Forge10.13.4.1566-1.7.10

Is it intended? Is there an option to disable that?

**Comment by Crudedragos** [comment]
See previous issue below, Unless something has fundamentally changed in NEI, there is nothing to be done.

https://github.com/ProjectZulu/JustAnotherSpawner/issues/78

**Comment by Crudedragos** [comment]
Thinking some more, but not recommending you may be able to still keep the NEI overlay by disabling the option in JAS to empty the default spawnlist and turn on the minecraft gamerule that prevents spawning: thus the vanilla spawnlist still exists but none of its entities will spawn. So NEI still shows an overlay (not based on what will actually spawn).

You will see an issue where there will be entities spawning from the vanilla spawnlist while the world is loading until the gamerule is activated the first time you load a world. The gamerule also doesn't stop vanilla chunk spawns.

In /config/JustAnotherSpawner/GlobalProperties.cfg change
"Empty vanilla spawnlists": true,   to    "Empty vanilla spawnlists": false,
and
"Turn gamerule spawning off on start": false,    to   "Turn gamerule spawning off on start": true,

**Comment by LemADEC** [comment]
Could we simply add a dummy mob in the spawn list?
Or maybe add an alternate overlay implementation into JAS?

**Comment by Crudedragos** [comment]
> Could we simply add a dummy mob in the spawn list?

Not really. You could create a real entity that despawns shortly after spawning, but that is still making the vanilla list spawn entities. Creating entities creates a large number potential issues and maintenance requirements to fix an issue in another mod. JAS would also need to become Client side, which I don't want to do.

In short, technically possible, but will not happen.

> Or maybe add an alternate overlay implementation into JAS? 

GUI support including overlays is something I want to do. But anything GUI related is far off in the future.
