### ISSUE TITLE
Vanilla squids spawns incorrectly on small water sources

### ISSUE THREAD

**Issue by lightning02** [ProjectZulu/JustAnotherSpawner#159]
i've tried JAS because Custom Mob Spawner from DrZarks add incompatibilites with some other mods and i and i noticed it works kinda fine . the only bad thing i noticed was that in small water areas happen that spids seems to spawn in invalid location and only thing that comes out is some inc sac up on the dirt around the water pool. 

http://i.imgur.com/u0fh5Ao.jpg

**Comment by noswanson1982** [comment]
I've noticed that there have been people who have messed around with triggers and made it so this wasn't a problem.  They essentially made it so squids couldn't spawn unless they had at least two water blocks in all directions around the squid.  That stopped the issue.  You might want to try to learn how the triggers work and give it a shot. :)

**Comment by lightning02** [comment]
that could be a solution in effect, btw, anyone know if is there also a line to disable all that massive spam in the game console? x_x

**Comment by Crudedragos** [comment]
Closed via c0d1169438d40da8528c7ba1306721bf5fa25f94
