### ISSUE TITLE
getting updated [1.10.2] code to author

### ISSUE THREAD

**Issue by frakier** [ProjectZulu/JustAnotherSpawner#163]
I really like this mod. Actually learning modding and java myself the past year off and on.
So anyway as a learning experiment I updated this mod to 1.10.2 let me know how to get the "src" folder to you. Honestly I did not expect to succeed just though of it as a learning experience.

Only issue that I have left besides more testing is monsters spawning stuck 1 block down. Which gets interesting when you come up on a garden of zombies. But I'm working on it.

**Comment by malpheas** [comment]
Just adding support to getting 1.10.2 update out there.

**Comment by frakier** [comment]
I figured out the age capability to replace the extended properties version, learned/learning about commands so I'm glad you put the code out there to play with. Leaned more in the last month about mods than in the past year.

**Comment by LunariusH** [comment]
Wait, this code exists?
