### ISSUE TITLE
MoCreatures spawnlist entry is regenerating with default values, under 0.16.1

### ISSUE THREAD

**Issue by Dulciphi** [ProjectZulu/JustAnotherSpawner#96]
-by "regenerating", I mean that my spawnlist entries are being overwritten with default values. As far as I can tell, it's only happening with the MoCreatures Spawn List Entries.

This spawnlist was working fine pre 0.15.. I've tried changing the  "FILE_VERSION" from "1.0" to "2.0".

I've tried manually re-editting it (which took ages. It would have to be MoCreatures <rolls my jaded eyeballs>) and I I've tried editing the first 2 entries of the regenerated file, saving, then using the command "/jas loadconfig". Those first 2 lines were reset to default values. I don't know what else to try. 

Is there a reason why it would just be MoCreatures?

**Comment by Radixy** [comment]
What'd you do to fix this? How do I fix it? I'm running Mo's creatures on my server with JAS and thousands of mobs are being spawned every minute, causing the server to lagg badly.

They DO spawn where they should but they spawn in too large quantities, nomatter how much I change the spawn cap or despawning timer / radius they keep on spawning each time i leave the area and return they're more.

What should I do?

how did you fix this?

Thanks in advance.

**Comment by Blue001** [comment]
Radixy, make sure you disable spawns done by MoCreatures itself.
Open the Mocreatures ini's and set all the spawn chances to 0.

Mo Creatures has always spawned WAY too many of every creature. Even if you disable vanilla spawns, they will still happen because Mo Creatures has its own system.

**Comment by Radixy** [comment]
####################
# ant
####################

ant {
    B:canspawn=false
    I:frequency=7
    I:maxchunk=4
    I:maxspawn=4
    I:minspawn=1
}


####################
# bear
####################

bear {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=4
    I:maxspawn=2
    I:minspawn=1
}


Etc... I've set all of them to false. If that's what you mean by ini. I just went to 
\minecraft\config\MoCreatures and edited the two cfg files.
